/**
 * ラダー図解析結果からC言語コードを生成する
 */
import type { LadderStructure, Manufacturer } from "./claude-vision";

const FILE_HEADER = `/**
 * Auto-generated C code from PLC Ladder Diagram
 * Generated by Ladder to C Converter
 * https://github.com/your-org/ladder-to-c
 */

#include <stdint.h>
#include <stdbool.h>

`;

const MITSUBISHI_TYPES = `/* === 三菱電機 PLC データ型 === */
typedef uint16_t WORD;
typedef uint32_t DWORD;
typedef bool BOOL;

/* デバイスアドレスマクロ */
#define X(n) input_X[n]   /* 入力リレー */
#define Y(n) output_Y[n]  /* 出力リレー */
#define M(n) relay_M[n]   /* 内部リレー */
#define T(n) timer_T[n]   /* タイマー */
#define C(n) counter_C[n] /* カウンター */
#define D(n) data_D[n]    /* データレジスタ */

`;

const KEYENCE_TYPES = `/* === キーエンス PLC データ型 === */
typedef uint16_t WORD;
typedef uint32_t DWORD;
typedef bool BOOL;

/* デバイスアドレスマクロ */
#define X(n) input_X[n]   /* 入力リレー */
#define Y(n) output_Y[n]  /* 出力リレー */
#define MR(n) relay_MR[n] /* 内部リレー */
#define T(n) timer_T[n]   /* タイマー */
#define C(n) counter_C[n] /* カウンター */
#define DM(n) data_DM[n]  /* データメモリ */

`;

const DEVICE_DECL_MITSUBISHI = `/* デバイス配列宣言 */
static BOOL input_X[256];
static BOOL output_Y[256];
static BOOL relay_M[8192];
static WORD timer_T[256];
static WORD counter_C[256];
static WORD data_D[8192];

`;

const DEVICE_DECL_KEYENCE = `/* デバイス配列宣言 */
static BOOL input_X[256];
static BOOL output_Y[256];
static BOOL relay_MR[4096];
static WORD timer_T[256];
static WORD counter_C[256];
static WORD data_DM[4096];

`;

/**
 * Claude の解析テキストをCコードのコメント付きスケルトンに変換する
 */
function wrapAnalysisAsCode(analysis: string): string {
  const lines = analysis.split("\n");
  const codeLines: string[] = [];

  codeLines.push("void plc_scan_cycle(void) {");
  codeLines.push("  /*");
  codeLines.push("   * ラダー図解析結果:");
  codeLines.push("   *");

  for (const line of lines) {
    // 空行はそのまま
    if (line.trim() === "") {
      codeLines.push("   *");
      continue;
    }
    // RUNG行はセクション区切りとして強調
    if (line.match(/^RUNG\s+\d+/i)) {
      codeLines.push("   * ------------------------------------------------------------");
      codeLines.push(`   * ${line.trim()}`);
    } else {
      codeLines.push(`   * ${line.trim()}`);
    }
  }

  codeLines.push("   */");
  codeLines.push("");

  // TODO スタブを出力
  const rungMatches = analysis.match(/RUNG\s+(\d+)/gi) || [];
  const rungNumbers = rungMatches.map((m) => parseInt(m.replace(/RUNG\s+/i, ""), 10));

  for (const rungNum of rungNumbers) {
    codeLines.push(`  /* --- Rung ${rungNum} --- */`);
    codeLines.push(`  /* TODO: Rung ${rungNum} の論理をここに実装 */`);
    codeLines.push("");
  }

  if (rungNumbers.length === 0) {
    codeLines.push("  /* TODO: 解析結果を元にラング処理を実装してください */");
  }

  codeLines.push("}");

  return codeLines.join("\n");
}

/**
 * ラダー構造からC言語コードを生成する
 */
export function generateCCode(
  ladder: LadderStructure,
  manufacturer: string
): string {
  const mfr = manufacturer as Manufacturer;
  const isMitsubishi = mfr !== "keyence";

  const parts: string[] = [
    FILE_HEADER,
    isMitsubishi ? MITSUBISHI_TYPES : KEYENCE_TYPES,
    isMitsubishi ? DEVICE_DECL_MITSUBISHI : DEVICE_DECL_KEYENCE,
    `/* 解析ページ数: ${ladder.pageCount} ページ */\n\n`,
    wrapAnalysisAsCode(ladder.rawAnalysis),
    "\n",
  ];

  return parts.join("");
}
